[project]
name = 'smart-expense-tracker'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.budget-planner]
path = 'contracts/budget-planner.clar'
clarity_version = 3
epoch = 'latest'

[contracts.transaction-parser]
path = 'contracts/transaction-parser.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
